// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListTasksParamsStatus enum.
func (e ListTasksParamsStatus) Valid() bool {
	switch e {
	case ListTasksParamsStatusCompleted:
		return true
	case ListTasksParamsStatusPending:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Data  User   `json:"data"`
	Token string `json:"token"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       string     `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Id          int64      `json:"id"`
	Status      TaskStatus `json:"status"`
	Title       string     `json:"title"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UserId      int64      `json:"user_id"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	Data []Task `json:"data"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Data Task `json:"data"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// IDParam defines model for IDParam.
type IDParam = int64

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FjdTuNGFH4Va9pLgwNFFfXdFnYRW5auIHQvUIQG+5DMYs+YmWNWKYrUh+gT9kmqM+OfOLY3CSRR1bvY",
	"mTk/3/nOmW/8wiKVZkqCRMPCF5ZxzVNA0Pbp/PQzPdNPIVnIMo4T5jPJU2AhEzHzmYanXGiIWYg6B5+Z",
	"aAIppx0PSqccaZ3En4+Yz3CagXuEMWg2m81ou8mUNGDdnSj5kIgI6XekJIK0P3mWJSLiKJQMvhol6V3t",
	"5kcNDyxkPwR1IoH71wTvtVb6qnDhHMZgIi0yMsbC2uPMZ5cKP6hcxrvzfqnQe7AuZz67kTzHidLiT9hh",
	"CA2vNopMqwiM4fcJvJcocLq7YP7giYitZQ9oLaMlxW4y/i7HSbWfyKpVBhqFY0/McWkIN4aI5zNUj2Aj",
	"LzhpUAs5Zo6RJaFvi2W+Mz2qGKzuv4LjzIkGjjDk5vEKnnIw2BHWfIothz6Lc7iLOUKjZejFHooUqNvy",
	"JKFqlB3WsoACE1ghGbusK4tmYVoZuFoste+Wddm/UGMhewGClIukkb1705Fpxo35pnS8QjCFiWpHV1xX",
	"MBYGQW86tFTIC5BjnLDw2N9EoESwdnTE7wQQ4juOr2dPZCn8XRttzjY5vdTH2zku4pWOFJ8Z5JibZXOA",
	"AL12K7/TQD7Ls3htcHID+m7FeBfIYE/Ucn8ZV5VTo1aN2Po4cyEMLh+YAiFdCTGLlfPDtebTVvy9c9JN",
	"yLdMbud/HX/XFRNA5iktz0DGVCS/bp253XUFbyyy/92p3krXHmutGPkzR67vcp10hviaxq8G4usbdP2W",
	"6mqScmzO5bheexBkm9ASqzGSBhNEuRY4vabtzss9cA2aVE399KEE5OOXISvUD1ly/9bgTBAzp6GEfFAt",
	"SrKTBLjc4zqaCIQIcw3eUMVKGPTmFJz3z19/e2meoNijseN7H78M90gRgkRaAvF+NYdCNszj3Hv3+Zz5",
	"7Bm0cY4O9gf7A0JUZSB5JljIfrKvfHtdsIkGzwcBWQ0SUgIWbuW6ikC3kZzHLHRCobhUgMFfVbw59dkQ",
	"IbNm3agFFy8jh4PBxnw3hGuH8P39NwLwaHDQZ6iKLFgU7EeHh6tsaqt6y8k8TbmeziGPfGyIx5aUI1pT",
	"1U4Xaqm/fKWe2lIFF+XaSkU82FkR3V3AFWXwy/KizN89N1TFEiGPexK+edTSvTVFbh4tRmPo6kRhcGhX",
	"+I1vArfFl4CnHPS0/hRQKZQayvUO3dloi+3XkkI9LTg3pW2m8/P5dkQhzjUMTVIsECoRdoiN6DrQ2SD1",
	"dXFLLdK+j+64SRpCb0mTvInzq9bJObSV6ijUfC8ELyKeuYOUWNqu3ql9X1WvgeBR+wS+VN5JAakdCUfL",
	"s60+Qa2VoourL0W/u8HPALszGeyMC+WptzVgzgD7UVmYal3+6yVB+SWUHGQco0kb0frWsKXmbl9Ldixj",
	"tlLQXQ0Ch97KgyAoT6vFr+JrcqX7HChs/+878BPXjxZyjxuvPv978SfFYoIUenXJGeAn2CZkjXvhJqX6",
	"uoMryrUGiYsijuKzgFl7+rnkZDPKCxXxxDuFZ0hUlhIoPrPfAey9MQyChBZMlMHweHA8sFQtPLyUms6G",
	"NvOrZ+d57oWr3Ww0+zcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
