// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for TaskActivityAction.
const (
	Created TaskActivityAction = "created"
	Updated TaskActivityAction = "updated"
)

// Valid indicates whether the value is a known member of the TaskActivityAction enum.
func (e TaskActivityAction) Valid() bool {
	switch e {
	case Created:
		return true
	case Updated:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListTasksParamsStatus enum.
func (e ListTasksParamsStatus) Valid() bool {
	switch e {
	case ListTasksParamsStatusCompleted:
		return true
	case ListTasksParamsStatusPending:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Data  User   `json:"data"`
	Token string `json:"token"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       string     `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PageInfo defines model for PageInfo.
type PageInfo struct {
	Count        int  `json:"count"`
	CurrentPage  int  `json:"current_page"`
	NextPage     *int `json:"next_page,omitempty"`
	PreviousPage *int `json:"previous_page,omitempty"`
	TotalData    int  `json:"total_data"`
	TotalPage    int  `json:"total_page"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Id          int64      `json:"id"`
	Status      TaskStatus `json:"status"`
	Title       string     `json:"title"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UserId      int64      `json:"user_id"`
}

// TaskActivity defines model for TaskActivity.
type TaskActivity struct {
	Action    TaskActivityAction `json:"action"`
	CreatedAt time.Time          `json:"created_at"`
	FieldName *string            `json:"field_name,omitempty"`
	Id        int64              `json:"id"`
	NewValue  *string            `json:"new_value,omitempty"`
	OldValue  *string            `json:"old_value,omitempty"`
	TaskId    int64              `json:"task_id"`
	UserId    int64              `json:"user_id"`
}

// TaskActivityAction defines model for TaskActivityAction.
type TaskActivityAction string

// TaskActivityListResponse defines model for TaskActivityListResponse.
type TaskActivityListResponse struct {
	Data []TaskActivity `json:"data"`
}

// TaskListData defines model for TaskListData.
type TaskListData struct {
	PageInfo PageInfo `json:"page_info"`
	Tasks    []Task   `json:"tasks"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	Data TaskListData `json:"data"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Data Task `json:"data"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// IDParam defines model for IDParam.
type IDParam = int64

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Page   *int                   `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int                   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fnbbtu2G38Vgf//pVI5WTB0vsuStkiXdkWbrhdFYLDSZ5uNRKrkR6deYGAPsSfckww86GRJsZXY3rA7",
	"Sya/0+87657EIssFB46KjO9JTiXNAEHap8uLd+bZ/GScjElOcU5CwmkGZExYQkIi4ZtmEhIyRqkhJCqe",
	"Q0bNjamQGUVzjuOPpyQkuMzBPcIMJFmtVua6ygVXYNmdCz5NWYzmdyw4Arc/aZ6nLKbIBI++KsHNu4rN",
	"/yVMyZj8L6oUidy/KnohpZDvPQvHMAEVS5YbYmRccVyF5K3Al0Lz5HDc3woMppblKiQfOdU4F5L9DgcU",
	"ocHVSpFLEYNS9EsKLzgyXB5OmN9oyhJLOQBzlpgj/rYhfqZxXt43zipFDhKZ856E4kYRPirjeCFBcQtW",
	"cu+TCiXjM+I8snDoz/5Y6EjflB4svnwF5zPnEijCNVW37+GbBoUdYtVVbDEMSaJhklCERsiYF0fIMjDR",
	"ptPUoFFEWIsCMkxhC2XssS4tmsC0NHBYbKTvjnXRvxIzxnsNBBllaUN796ZD05wqdSdksoUwnkR5o0uu",
	"d3QGl3wq2jLFQjtvX89ZIYm1lMBxktMZdJ/g8L36uwe92vFcwoIJrQZcQYE0nRQO3/d/n4RrpnK6rinW",
	"4NEg2GXI9zBjCkHuGuOM8SvgM5yT8fNwF4ibSO1CO8tTQEgmFB8fhrHNBQ/SaAd/Mzls5PH0ZMGSrWpz",
	"SBRS1GpTQjUG/eBOPpCJQqLzZLBxtAI52VLeNWewrUlxv5Cr1KmBVUO2Pp85i5EtfC1s+g6NC/A2mamg",
	"ceZuPNJjpgzSZOI6sPsdws3hbrKgqd6OrEiTAaeRqtvJ1pI8FfaCW90BPEoNk2/C+qxEFrjObKZ0lyuX",
	"qdGotK3TuGIKN3csDCFTQ1zIGtXxpVLSZcsQvQ2LoWKEuvCsmwKZBD9hviI+JExZOT26apAaG8V3JMOa",
	"PA/p8rSWsGGRQXZ8Ot9h/D6UGblwyBx4YrwurEpYp0t+tO76721TW+raPr2daxcUqZxomXaK+Jh0WjYm",
	"j8+cw0tbV9Yq2peajsPKlDHZLoaj7TzSNAgQa8lw+cFcd1y+AJUgzZhWPb0sDPL60zXx45yh5P6tjDNH",
	"zN1QWCSgtVE9BcqPqIznDCFGLSG4FolgCoPaSBr89cefQaZTZEcm+4fB60/XR2bEBY7mCCTPyn5gTK51",
	"ooOzd5ckJAuQyjE6fjZ6NrJFLgdOc0bG5Af7KrT7D6totDiODNUoNaONNbdwUWWMbiW5TMjYTT5+SwIK",
	"fxbJ7sbpxlS1auJmQnB9u3IyGu2Md2MS75jkf/3FGPB0dNxHqJQsWt9AnJ6cbHOpvaawPqmzjMplzfJI",
	"Z8r4sXXKG3OmxE76qaUfvmKu2ROC62PTViAeHwzEc9/uWCR/2gxKfZm2IxQLCwU04HAXmJDuxbTsQ2bQ",
	"FYlM4XXZVlRLzs9+tflNg1xWu81yUqhMOazorsJuwn66rsgmMKU6RTI+Ds28yzLD5bir1e0mmLKMYTfF",
	"k1FIMvrdkxyNNjC42WPCaPVqPUmjVlcsNvWK8vnGiFgLcZP7i1ax8AmH8c0q7AnpamO3p6BurwQPHNaN",
	"1nRDWD8pSrfFyTG0SHUAVY/e6J4lK+fCJq7a6F3Y9yV6DQuetnuGtyI49ya1Sex0s7blV4BBKjq5+lQM",
	"u1PSK8BuTUYH84WiTu/NMK8A+62yloe7+FdHouJjlGGQU4znbYtWc86egrs9SB248doLoIdKBM56WyeC",
	"iLp1hx9hHizrZ9XRPVu/c7XzT4RWWf4Cb6dlMGcKhW0OdhdsbViKtmf9e/HAEO4uz572fz4xvqHy1qOn",
	"gqqR7A0L0/qqyG19+6rJG9inyRoLhl3OfEPrif9QtT4NGPmswSw9uSh8sinllYhpGlzAAlKRZ2C/fNmF",
	"kl1AjKMoNQfmQuH4+ej5yLqq53BftNxWNNOP+2fHufbCYbe6Wf0dAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
