// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for TaskActivityAction.
const (
	Created TaskActivityAction = "created"
	Updated TaskActivityAction = "updated"
)

// Valid indicates whether the value is a known member of the TaskActivityAction enum.
func (e TaskActivityAction) Valid() bool {
	switch e {
	case Created:
		return true
	case Updated:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListTasksParamsStatus enum.
func (e ListTasksParamsStatus) Valid() bool {
	switch e {
	case ListTasksParamsStatusCompleted:
		return true
	case ListTasksParamsStatusPending:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Data  User   `json:"data"`
	Token string `json:"token"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       string     `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Id          int64      `json:"id"`
	Status      TaskStatus `json:"status"`
	Title       string     `json:"title"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UserId      int64      `json:"user_id"`
}

// TaskActivity defines model for TaskActivity.
type TaskActivity struct {
	Action    TaskActivityAction `json:"action"`
	CreatedAt time.Time          `json:"created_at"`
	FieldName *string            `json:"field_name,omitempty"`
	Id        int64              `json:"id"`
	NewValue  *string            `json:"new_value,omitempty"`
	OldValue  *string            `json:"old_value,omitempty"`
	TaskId    int64              `json:"task_id"`
	UserId    int64              `json:"user_id"`
}

// TaskActivityAction defines model for TaskActivityAction.
type TaskActivityAction string

// TaskActivityListResponse defines model for TaskActivityListResponse.
type TaskActivityListResponse struct {
	Data []TaskActivity `json:"data"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	Data []Task `json:"data"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Data Task `json:"data"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// IDParam defines model for IDParam.
type IDParam = int64

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FnbbttGE34VYv//kg7l1ChS3qnOAUmdNEiU5iIQhDU5kjYmd+ndoQzVENCH6BP2SYrZ5VGkLMmW1KJ3",
	"Ir2c0/fNaX3PIpVmSoJEw8J7lnHNU0DQ9unty4/0TD+FZCHLOM6ZzyRPgYVMxMxnGm5zoSFmIeocfGai",
	"OaScvpgqnXKkcxJ/vGA+w2UG7hFmoNlqtaLPTaakAavuUslpIiKk35GSCNL+5FmWiIijUDL4bpSkd7Wa",
	"/2uYspD9L6gdCdxfTfBKa6U/FSqcwhhMpEVGwlhYa1z57IPC1yqX8em0f1DoTa3Klc++SJ7jXGnxO5zQ",
	"hJZWa0WmVQTG8OsEXkkUuDydMb/xRMRWsgd0ltGR4msSPsxxXn1PZNUqA43CsSfmuNWEL4aI5zNUN2At",
	"LzhpUAs5Y46RJaG/Fcd8J3pcMVhdfwfHmUsNHGHEzc0nuM3BYI9ZTRc7Cn0W5zCJOUIrZejFGYoUKNvy",
	"JCE0ygzrSECBCezgjD3W50UbmI4HDout8t2xPvlXaibkxgBBykXS8t696fE048bcKR3vYEwhovqiz65P",
	"MBMGQR/atFTIK5AznLPwhX8IQ4lgXeuI3wkgxBOOj2dPZCn8oIwuZ9uc3qrj6RwX8U4txWcGOeZmWx2g",
	"gH52Jx9IIJ/lWbx3cHIDerKjvWtksB21/L60q/KphVXLtk2cGUYoFkUJb3OHRyV428JUyhi6Lx7JmKmA",
	"JJ64weH+gHBLuJsseJLvJlYl8R6nkZubyc6WPBX2UluTAAVKrZBvw3pYIQsyT0l88XFNmYaM2tumjCth",
	"cHujFQip2YdCNqhOL9eaLzuB2NhnScqBjXqaMU8bQ5z+ffR9rspaiWoGMibo/LoP9OL6xWL+7x1ROu7a",
	"Ga1bsBYcuZ7kOuk18TE1qerujy8/+/eHvtQvZ4CGj/vVegrZIQbj3RhJXRaiXAtcfqbPnZZr4Bo0jej1",
	"0+syIO++jlgxypMk99c6OHPEzC0EQk5Vh5LsMgEuz7iO5gIhwlyDN1KxEga9xjri/fXHn16aJyjOqIT6",
	"3ruvozNab0AiHYH4WdVUQzbK49wbfnzLfLYAbZyi82eDZwPbKTKQPBMsZD/YV77dfa2jweI8IKlBQmOt",
	"DbdyWUVBt5a8jVnopt5iQwaDP6v4cKtUa6JetXGjFFzfrJ8PBgfT3drCera4X3+hAF4MzjcJqiwL1rfP",
	"i+fPd/mou6JaTuZpyvWyEXnkM0M8tqQc05kKO12M/pvhK5eDIyG4vnvsBOL5yUC8LGYGi+RP20FpXqQc",
	"CMUyQh73JNx5lNIbMaXhycZoBn2ZKAyO7Am/dcH1rbjWus1BL+t7rWrcrkO5X9NdjY+Yfp1RaEMKNqq0",
	"9bRZn7+NycRGwlAlxSJCZYRdxMa02/YmSH33caQU6V6unDhJWoPeliR5Eud3xckptEj1ANXMheBexCvX",
	"SImlXfRe2vcVeq0IXnQ78AflXRYhtSXhYru31X3qXi46uza56Pcn+BvAfk8GJ+NC2fWOFpg3gJujslbV",
	"+vTXR4LyWp8UZByjeTei9dZwpOTuriUnHmOOAuipCoGL3s6FIOBuAy8Wggeb5LA+euTo9942/BOpVbU/",
	"r4jT0psLg8oOBYdLti4s5RCx/p+3PVO4vz0Xsv/zhfE91zcFesarx7KNaUGDpAncReSmbvIejhmy1rp+",
	"yA1q334S5VqDxPXZmuyzAbPy9KLkZNvKKxXxxHsJC0hUllJQfGavZ+w6HwZBQgfmymD4YvBiYKlaaLgv",
	"R21r2sqvnp3mxguH3Wq8+jsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
